name: economic-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10
  
  # Core data science packages
  - pandas=2.1.1
  - numpy=1.25.2
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # Jupyter for interactive analysis
  - jupyter=1.0.0
  - jupyterlab=4.0.6
  
  # Economic data packages
  - wbdata=0.3.0
  - fredapi=0.5.0
  
  # Visualization
  - plotly=5.15.0
  
  # Machine learning
  - scikit-learn=1.3.0
  
  # Utilities
  - pip
  - pip:
    - yfinance==0.2.18
    - alpha-vantage==2.3.1
