name: economic-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10
  
  # Essential data science packages
  - pandas=2.1.1
  - numpy=1.25.2
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # Jupyter for interactive analysis
  - jupyter=1.0.0
  - jupyterlab=4.0.6
  - ipykernel=6.25.2
  
  # Economic data packages
  - wbdata=0.3.0
  - fredapi=0.5.0
  
  # pip for additional packages
  - pip
  - pip:
    - yfinance==0.2.18
    - alpha-vantage==2.3.1
